// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PressKeyOKCode is the HTTP code returned for type PressKeyOK
const PressKeyOKCode int = 200

/*PressKeyOK empty on success

swagger:response pressKeyOK
*/
type PressKeyOK struct {

	/*empty on success
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPressKeyOK creates PressKeyOK with default headers values
func NewPressKeyOK() *PressKeyOK {

	return &PressKeyOK{}
}

// WithPayload adds the payload to the press key o k response
func (o *PressKeyOK) WithPayload(payload string) *PressKeyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the press key o k response
func (o *PressKeyOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PressKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
