# Example configuration as TOML file

title = "Configuration example"

[global]
interface="en0"
no_of_soundtouch_systems=7

[logger]
speakers = ["Office"]
ignore_messages = ["ConnectionStateUpdated"]
terminate  = false

[episodeCollector]
speakers = ["Office"]
artists = ["Drei Fragezeichen", "Umberto Eco"]
terminate  = false
database = "episodes.db"

[magicZone]
## ordered list of speakers that should be grouped in zones. All if empty.
# speakers = ["Office", "Kitchen"]

## terminate indic ates whether no further plugin will be called after this plugin has been executed
# terminate = false